---
- name: "file: create {{ workdir }} directory if not exists"
  file:
    path: "{{ work_dir }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755

- name: "copy: copy .dockerignore file"
  copy:
    src: "{{ role_path }}/files/.dockerignore"
    dest: "{{ work_dir }}/.dockerignore"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755

- name: "template: transfer docker-compose template to remote"
  template:
    src: docker-compose.yml.j2
    dest: "{{ work_dir }}/docker-compose.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755
    force: yes

- name: "include_role: Install auditd audispd-plugins"
  include_role:
    name: install_packages
  vars:
    state: present
    packages:
      - "auditd"
      - "audispd-plugins"

- name: "file: create 'filebeat_home' directory if not exists"
  file:
    path: "{{ work_dir }}/filebeat_home"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755

- name: "template: transfer docker-compose template to remote"
  template:
    src: filebeat.yml.j2
    dest: "{{ work_dir }}/filebeat_home/filebeat.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755
    force: yes

- name: "change ownership of filebeat.yml"
  file:
    path: "{{ work_dir }}/filebeat_home/filebeat.yml"
    owner: 0
    group: 0


- name: "docker-compose: run filebeat compose-file"   
  docker_compose:
    project_src: "{{ work_dir }}"
    files:
      - docker-compose.yml
    build: yes
    state: present
    restarted: yes