---
- name: "file: create {{ workdir }} directory if not exists"
  file:
    path: "{{ work_dir }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755

- name: "copy: copy .dockerignore file"
  copy:
    src: "{{ role_path }}/files/.dockerignore"
    dest: "{{ work_dir }}/.dockerignore"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755

- name: "template: transfer docker-compose template to remote"
  template:
    src: docker-compose.yml.j2
    dest: "{{ work_dir }}/docker-compose.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755

- name: "file: create 'grafana_home' directory if not exists"
  file:
    path: "{{ work_dir }}/grafana_home"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755


- name: "file: create directory for config if not exists"
  file:
    path: "{{ work_dir }}/grafana_home/config/"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755
    recurse: yes

- name: "copy: copy config.ini file"
  copy:
    src: "{{ role_path }}/files/config.ini"
    dest: "{{ work_dir }}/grafana_home/config/grafana.ini"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755  

- name: "docker-compose: run grafana compose-file"   
  docker_compose:
    project_src: "{{ work_dir }}"
    files:
      - docker-compose.yml
    build: yes

- name: "Recursively change ownership of a directory to grafana"
  file:
    path: "{{ work_dir }}/grafana_home/"
    state: directory
    recurse: yes
    owner: 472
    group: 472