# List of apt packages to be installed
packages:
  - "aptitude"
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "software-properties-common"
  - "python3-pip"
  - "virtualenv"
  - "python3-setuptools"
  - "mc"

# State of packages
state: latest
