---
    - name: Download backend artifact
      maven_artifact:
        group_id: 'backend-training-multi-branch-pipeline'
        artifact_id: 'backend-training'
        version: '{{ branch }}_{{ version }}'
        repository_url: 'http://nexus.alavr.test.coherentprojects.net/repository/backend/'
        username: '{{ nexus_username }}'
        password: '{{ nexus_password }}'
        dest: /opt/backend.jar
      become: yes

    - name: delete file environment
      ignore_errors: yes
      file:
        state: absent
        path: "/etc/environment"
      become: yes

    - name: create file environment
      ignore_errors: yes
      file:
        path: "/etc/environment"
        state: touch
      become: yes

    - name: add lines
      lineinfile: 
        dest: "/etc/environment"
        line: '{{ item }}'
      with_items:
        - "export DB_URL={{ db_url }}"
        - "export DB_USERNAME={{ db_username }}"
        - "export DB_PASSWORD={{ db_password }}"
        - "export DB_PORT={{ db_port }}"
        - "export DB_NAME={{ db_name }}"
        - "export JDBC_DRIVER={{ jdbc_driver }}"
      become: yes

    - name: Run jar
      shell: 'java -Dserver.port=80 -jar /opt/backend.jar'
      become: yes

